services:
  - type: web
    name: pmgold-n8n
    env: docker
    plan: free
    branch: main
    healthCheckPath: /
    dockerCommand: "n8n start"
    ports:
      - port: 5678
        protocol: tcp
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "http"
      - key: GENERIC_TIMEZONE
        value: "Asia/Dubai"
